class Map(Exception): ...


class MapNameIsTooLong(Map): ...

class MapNameIsTooShort(Map): ...

class TaskDescriptionIsTooLong(Map): ...

class TaskDescriptionIsTooShort(Map): ...

class DeniedAccessToTopMap(Map): ...

class NoCurrentUser(Map): ...

class NoTopMap(Map): ...

class NoTask(Map): ...

class NoTaskOwner(Map): ...

class DeniedAccessToTask(Map): ...

class UnknownTaskStatus(Map): ...
