class Map(Exception): ...


class MapNameIsTooLong(Map): ...

class MapNameIsTooShort(Map): ...

class TaskDescriptionIsTooLong(Map): ...

class TaskDescriptionIsTooShort(Map): ...

class DeniedAccessToTopMap(Map): ...

class NoCurrentUser(Map): ...

class NoTopMap(Map): ...
