version: "3.9"
services:
  app:
    build: .
    container_name: todo-app
    network_mode: host
    volumes:
      - .:/todo
    depends_on:
      - postgres
      - redis
    command: ["scripts/start.sh", "python", "manage.py", "runserver"]
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    container_name: todo-postgres
    network_mode: host
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: todo-redis
    network_mode: host
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "todo"]

  nginx:
    image: nginx:alpine
    container_name: todo-nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

volumes:
  db: null
