# Generated by Django 4.2.6 on 2024-01-03 21:02

import apps.shared.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=154, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('x_section', models.PositiveIntegerField()),
                ('y_section', models.PositiveIntegerField()),
                ('next', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(apps.shared.models._VisualizableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=128)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'done'), (3, 'failed')], default=1)),
                ('color', models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth'), (5, 'fifth'), (6, 'sixth')])),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.shared.models._VisualizableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remove_on', models.IntegerField(choices=[(1, 'active'), (2, 'done'), (3, 'failed')], default=2, null=True)),
            ],
            bases=(apps.shared.models._VisualizableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('settings', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.tasksettings')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.space')),
                ('tasks', models.ManyToManyField(related_name='zones', to='shared.task')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.shared.models._VisualizableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('repetition_time', models.DurationField(blank=True, default=None, null=True)),
                ('new_status', models.IntegerField(choices=[(1, 'active'), (2, 'done'), (3, 'failed')], default=None, null=True)),
                ('new_is_hidden', models.BooleanField(blank=True, default=None, null=True)),
                ('is_deleter', models.BooleanField(blank=True, default=False)),
                ('x_vector', models.IntegerField(blank=True, default=0)),
                ('y_vector', models.IntegerField(blank=True, default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shared.tasksettings')),
            ],
            bases=(apps.shared.models._VisualizableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='task',
            name='settings',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.tasksettings'),
        ),
        migrations.AddField(
            model_name='task',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.space'),
        ),
        migrations.AddField(
            model_name='task',
            name='subspace',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root', to='shared.space'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shared.tasksettings'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='shared.task'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
