# Generated by Django 4.2.6 on 2024-01-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_taskevent_task_to_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='x_section',
            new_name='user_x',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='y_section',
            new_name='user_y',
        ),
    ]
