# Generated by Django 4.2.10 on 2024-02-29 05:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_rename_x_section_space_user_x_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.HashIndex(fields=['name'], name='shared_user_name_da4a4b_hash'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.HashIndex(fields=['email'], name='shared_user_email_11abfe_hash'),
        ),
    ]
