# Generated by Django 4.2.10 on 2024-02-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_user_shared_user_name_da4a4b_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksettings',
            name='remove_on',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'done'), (3, 'failed')], default=2),
        ),
    ]
