from apps.shared.errors import Application


class Access(Application): ...


class Registration(Access): ...

class UserExists(Registration): ...

class NoUser(Registration): ...

class EmailConfirmation(Registration): ...
