from apps.access.lib import Application


class Access(Application): ...



class User(Access): ...

class NoUser(User): ...

class UserExists(User): ...


class Username(User): ...

class UsernameExists(Username, UserExists): ...

class UsernameLength(Username): ...

class UsernameTooShort(UsernameLength): ...

class UsernameTooLong(UsernameLength): ...


class Email(User): ...

class EmailExists(Email, UserExists): ...


class Password(User): ...

class NoPassword(Password): ...

class PasswordMismatch(Password): ...

class PasswordPower(Password): ...

class WeakPassword(PasswordPower): ...

class MediumPassword(PasswordPower): ...

class PasswordTooLong(Password): ...


class PasswordHash(Password): ...

class NoPasswordHash(PasswordHash): ...


class Confirmation(Access): ...

class EmailConfirmation(Confirmation): ...
