name: Test

on: push

jobs:
  pytest-django:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: install dependences
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-django
      - name: pytest
        run: pytest
