class Access(Exception): ...


class NoUser(Access): ...

class UserExists(Access): ...

class UsernameExists(Access): ...

class UsernameLength(Access): ...

class UsernameTooShort(Access): ...

class UsernameTooLong(Access): ...

class EmailExists(Access): ...

class NoPassword(Access): ...

class IncorrectPassword(Access): ...

class PasswordMismatch(Access): ...

class PasswordTooLong(Access): ...

class PasswordTooShort(Access): ...

class PasswordWithoutAsciiLowercase(Access): ...

class PasswordWithoutAsciiUppercase(Access): ...

class PasswordWithoutDigits(Access): ...

class PasswordWithoutPunctuation(Access): ...

class NoPasswordHash(Access): ...

class Confirmation(Access): ...

class EmailConfirmation(Access): ...
